### ISSUE TITLE
Make all toplevel keys required

### ISSUE THREAD

**Issue by jhass** [jhass/nodeinfo#1]
Should we make all toplevel keys required and all substructure keys as well? This would make it easier for the client developers, while it might make the server developers jobs a little bit harder.

**Comment by svbergerem** [comment]
When you do that I think one has to be able to distinct between "no services available" and "I won't tell you which services I enabled".

**Comment by jhass** [comment]
Well, is that relevant to know?

**Comment by jhass** [comment]
Okay, we'll make all keys that point to a substructure required, that will make the protocol key required too. To go full there I will also require at least one entry for inbound and outbound there.

This is to make life easier for client developers. However clients should not draw any conclusion from the absence of an optional key.
