### ISSUE TITLE
redmatrix is not a protocol (and is a discontinued project)

### ISSUE THREAD

**Issue by redmatrix** [jhass/nodeinfo#11]
For now hubzilla sites will respond as 'redmatrix' entities, but this is not strictly correct. The actual protocol name is 'zot'.

**Comment by jhass** [comment]
Was it called `zot` for RedMatrix already too? Will RedMatrix be updated (to `zot`) if we drop `redmatrix` as a protocol name?

**Comment by redmatrix** [comment]
The protocol was always zot. Redmatrix still exists but is essentially an abandoned development tree and will probably not ever support nodeinfo.  Anyway I can use whatever works but I find it a bit awkward that compatibility with a project in NodeInfo is taken as compatibility with a protocol. I believe the underlying goal of these fields in NodeInfo are to answer the question "what protocol stacks does this pod/hub/whatever support?" and to answer it with project names probably isn't the most ideal response because they are apples and oranges. 

The protocol stacks we see most often on the open web are OStatus, Diaspora, DFRN, zot, activitypub (was pump.io), micropub, tent, and E/SMTP.  There are probably a dozen more if you open the definition to include instant messaging protocols.

Was also considering how to make NodeInfo more extensible as the traditional "social network" landscape changes over time. The thing that's trying to be fixed is the variety of ways you can spell a project name like GNU-Social (talking about the API federation section now). I think if this was turned into a simple ruleset where [a-z] are the only allowed characters it works with everything that is there now and lets this extend to future services or existing services which aren't in the list for whatever reason - e.g. vk or baidu or hubzilla. 

Anyway I'll close this as a fixed issue but just providing feedback which you are free to accept or reject as you see fit.
