### ISSUE TITLE
Catalogue - discussion

### ISSUE THREAD

**Issue by pierreozoux** [jhass/nodeinfo#19]
Hello!

We created this project, and are really excited!

https://github.com/libresh/catalogue/ (look also at the issues, there are links to various other things)

Actually, we've been redirected to your project, and I'm amazed but what you already did.
Now I'm curious, and I have a lot of questions:
 - do you use schema.org? If not, why?
 - why not using json-ld?
 - why not exposing this json-ld inline in the index.html ? (as it would also benefit SEO)

(Let me know if it is not the right place to discuss those)

Thanks for your time and have a nice evening!

**Comment by jhass** [comment]
Hey, 
the reason is because this was initially just an afternoons work and I didn't want to do a week of research and learning for it nor impose that amount of work to any implementers. I didn't see a need or purpose to fit this into an existing ecosystem since it's there to enhance a new one.

**Comment by pierreozoux** [comment]
Sorry, I didn't get your answer, does it mean that you interested in collaborating or not?

**Comment by jhass** [comment]
Me, personally probably not.

**Comment by pierreozoux** [comment]
We'll PR a new schéma if needed, and will discuss there then.
