### ISSUE TITLE
Comments from other networks

### ISSUE THREAD

**Issue by jaywink** [jhass/nodeinfo#3]
I thought this might be the easiest way to collect comments on whether something could be changed before merging in and implementing in d* for example.

[Comment from](https://iliketoast.net/posts/604543#6f2231b7c19aaa9902352cae4e4a3bbb6911cf735122957fac75054539c22c97@zothub.com) Mike Macgirvin @ RedMatrix:

> I already looked at that - no issues. I can pull that together fairly quickly. We’ve already got something which is more tailored for the kind of info we need, off the top it also includes things like what plugins are installed and what service_class restrictions might be in place (like free accounts get 5MB of photo space and a maximum of 200 friends - useful for making a choice which site to join); and also gives a contact email for a site admin. There’s some less useful stuff like the last time a background cronjob occured. This lets us probe a site that’s having communication difficulties and often be able to tell them why without having to read their minds. So NodeInfo is fine but keep it extensible. There’s a fair bit of stuff that it’s useful to know about a site without requiring one to send out a post and say “hey - who runs xyz.com? We need to ask them something…”
> 
> ok - one potential issue, for other cross-post networks we’ve got a fair number (a dozen or so) and we might need to agree on the names we use. They’ll probably be straightforward but if your connector is gnu-social and mine is gnusocial (or even statusnet) or mine is google and yours is google+ we might have to sort out which canonical name the protocol should use.

**Comment by jhass** [comment]
No further general discussion and specific points got their own issues. Closing.
