### ISSUE TITLE
Add element for source code repository

### ISSUE THREAD

**Issue by zcdunn** [jhass/nodeinfo#31]
I propose that an optional field is added to the `software` object, with a url to a source code repository as the value, so open source projects can advertise their code.

There are current implementors that are using a `github` key in their metadata:
- [p3k](https://aaronparecki.com/.well-known/nodeinfo.json)
- [Write Freely](https://write.as/api/nodeinfo)
- [PixelFed](https://pixelfed.social/api/nodeinfo/2.0.json)

My own software, [Booth](https://adhoc.systems/nodeinfo/2.0), is hosted on GitLab so I chose a more generic `repo` key.

Standardizing this key would clear up this discrepancy and provide a simple way for trackers such as [fediverse.network](https://fediverse.network) to provide a link to source code. You can see at https://fediverse.network/pixelfed that there is a source code link, but the maintainer has to find and add those links manually.

**Comment by jhass** [comment]
Sounds good to me, feel free to make a pull request :)

However I wouldn't like to release a new version with just this change, but rather pile up a couple more first.

**Comment by zcdunn** [comment]
👍 So, should my PR modify `2.0/schema.json` or start the new version that you can release when ready?

**Comment by jhass** [comment]
Oh, right. New version makes sense I guess. Let's make it 2.1, can always rename later :)

**Comment by pfefferle** [comment]
but doesn't that mean that all providers have to upgrade the version number or perhaps provide a new discovery endpoint?

I would prefer changing version numbers only if the structure changes and not with every added value/enum.

**Comment by jhass** [comment]
The advantage of bumping the version is that it doesn't introduce uncertainty, especially when we add new required fields consumers could no longer rely on the fact that they must be present if the schema could just change without a version change.

**Comment by pfefferle** [comment]
I am so sorry, I haven‘t read the issue properly! Shame on me! I just read about the new platforms and not the new key(s) that were introduced! It totally makes sense to update the version number in that case! Sorry!

I also support the repo idea, because for wordpress there are different implementations, so it is both wordpress as a software, but different plugins -> repos.

**Comment by pfefferle** [comment]
Nevertheless, I would vote for `repository`, that is also what npm and composer are using and it matches better with the other nodeinfo keys.
