### ISSUE TITLE
Add element for profile directory

### ISSUE THREAD

**Issue by drequivalent** [jhass/nodeinfo#38]
In Mastodon, there's an opt-in profile directory:

https://mastodonsocial.ru/explore

IMO, it would be great to standardize it, to ensure better account exposure across nodes for those who want it.

In Nodeinfo JSON document, there would be a link to another JSON document containing the directory itself in standardized format. For example,
```
"directory" : "https://mastodonsocial.ru/.well-known/profiles.json"
```
In profiles.json there would be links to standard Profile objects along with their infos like bios etc.

**Comment by jhass** [comment]
I'm not sure this is the right place for that. NodeInfo's goal is to allow statistics collection about the federated social  network world. This is rather trying to standardize a profile directory protocol into it.

So I'm going to close this for now, this doesn't mean you cannot argue against the above point :)
