### ISSUE TITLE
Additional entries for services

### ISSUE THREAD

**Issue by jhass** [jhass/nodeinfo#4]
The current valid values for  `services` are `diaspora`, `facebook`, `tumblr`, `twitter`, `wordpress`. 

What are other services implemented today? #3 mentioned `google` and `gnusocial`/`statusnet`, anything else to add?

**Comment by redmatrix** [comment]
appnet, blogger, dreamwidth, insanejournal, smtp, libertree, livejournal, posterous, pumpio, redmatrix, friendica, myspace, linkedin, drupal, and I've also seen tent, pinterest, and xmpp in the wild.

**Comment by jhass** [comment]
Oh, Redmatrix allows pushing a post to somebody via XMPP and SMTP while authoring it? Note `services` is meant as "also post it with my account over there`, for "supports interop with" there's the `protocols` key (which probably should too be extended by a few more valid values).

**Comment by redmatrix** [comment]
We call them crosspost connectors. Friendica crossposts to specific email recipients (and also provides protocol interop, meaning email connections can appear as contacts and you can converse from your stream and put them into aspects). They're separate mechanisms.  I'm not certain the scope of the XMPP connector but it was a guy who I know was associated with buddycloud. I don't know if it ever worked, but we had a few exchanges on how to build a plugin.

**Comment by jhass** [comment]
Doesn't do buddycloud its own protocol ontop of XMPP? So I can see `buddycloud` as service if they have an application API and as protocol for interop. I also can see `xmpp` as service, though as protocol I'm not sure, since standard XMPP doesn't really work for the social network type of communication, IME.

**Comment by redmatrix** [comment]
They do - again I don't the know the scope and never actually saw the code. It might have been their REST API, and it might have been pushing XMPP messages over BOSH. 

But we do have a few places where we provide both protocol interop and crossposting over API. (Diaspora, Friendica, redmatrix, smtp). Some folks prefer to use one or the other to have a choice in which identity which ends up as the author.

**Comment by jhass** [comment]
Yes, which is why I have separate keys in the first place, so we can tell which node supports what exactly.

**Comment by jhass** [comment]
So let's group what we gathered so far.

**Not federated social network/publishing platform**

* appnet
* blogger
* dreamwidth
* drupal
* facebook
* google
* insanejournal
* linkedin
* livejournal
* myspace
* pinterest
* posterous
* tumblr
* twitter
* wordpress

These should be uncontroversial to be valid for `services` only.

**With (inofficial) API and existing crossposting implementations**

* buddycloud (?)
* diaspora
* friendica (?)
* gnusocial
* libertree (?)
* mediagoblin (?)
* pumpio (?)
* redmatrix (?)
* tent (?)
* smtp
* xmpp

After verifying existing implementations or official API for crossposting to the entries makred with (?), adding those to `services` should be uncontroversial.

**Federated**

* buddycloud
* diaspora
* friendica
* gnusocial
* libertree
* mediagoblin
* pumpio
* redmatrix
* tent

These for now should be the valid items for entries under the `protocols` keys.

Makes sense? Something else I missed?

**Comment by redmatrix** [comment]
I can personally verify API posting for

diaspora (F,R via HTML scraping)
friendica (R)
gnusocial (F,R)
libertree (F,R)
pumpio (F,R)
redmatrix (R, yeah I know it's weird, but we've got it and people use it)
smtp (F)

mediagoblin (R, still under development, early releases were pretty buggy)

That leaves tent, buddycloud, and xmpp as unconfirmed for API federation from my point of view, although I believe XMPP API posting is available from statusnet/gnusocial

**Comment by redmatrix** [comment]
Oh and as mentioned earlier, SMTP is a federated protocol for Friendica.

**Comment by redmatrix** [comment]
We'll also ignore hubzilla for the moment..

**Comment by jhass** [comment]
I decided to add the unverified values too, we can remove them in a future version if they turn out useless. Please open separate issues to discuss each addition/removal from now on.
