### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by pfefferle** [jhass/nodeinfo#44]
The Website seems to be not updated in 3 years. Is there a script to generate the GH-Page from the master or do we have to reuqest changes as MRs?

**Comment by jhass** [comment]
There simply wasn't any changes :) Merge/Pull requests are welcome, I'll take care of the rest!

**Comment by pfefferle** [comment]
The support list was updated in the README https://github.com/jhass/nodeinfo#support and there was some work on v2.1. That's why I asked.

**Comment by jhass** [comment]
You're right, I missed redeploying after the readme updates, my bad :) 

As for 2.1, I guess back then my plan was to accumulate a few more changes, but since there hasn't been any requests into that direction since then, I guess we could release it.

**Comment by jhass** [comment]
All up-to-date :)
