### ISSUE TITLE
Free form metadata

### ISSUE THREAD

**Issue by jhass** [jhass/nodeinfo#5]
Should there be a way to add free form, non-standard metadata? Potential structure:

```json
{
  ....
  "metadata":  {
    "some_key": "some_value",
    "another_key": 42,
  }
}
```
 
Where the keys and values are completely free-form and not to be relied upon by standard clients.

**Comment by jhass** [comment]
@jaywink I think we should do this for things like chat.

**Comment by svbergerem** [comment]
#3 shows some additional metadata for redmatrix so I agree that this could be useful.
