### ISSUE TITLE
two fetches (?)

### ISSUE THREAD

**Issue by redmatrix** [jhass/nodeinfo#6]
Just looking over the doco again - is there any reason why this couldn't be collapsed into just fetching the data from .well-known/nodeinfo (?) instead of fetching a URL pointer and having to do another fetch to get the data (?) . Seems a bit wasteful. The only reason I can see for another layer of indirection is to support alternative mime-types; but these aren't supported currently and if I recall webfinger may have a more elegant way of negotiating content-type, while delivering the data in the first fetch for the case of json.

**Comment by jhass** [comment]
The idea is that a node can provide multiple, fully incompatible versions and that a client can read multiple fully incompatible versions without any amount of guessing or pre-parsing. Determining it only over a version inside the document disallows moving and changing the structure of that indication and as said is harder to parse, especially in statically typed languages you easily end up parsing it twice, if possible at all.

**Comment by jaywink** [comment]
I do tend to agree with @redmatrix that having to do two fetches seems a bit over engineered for the need and use cases of NodeInfo. I'm not sure why a node would want to provide two incompatible versions? What is the use case?
