### ISSUE TITLE
Loosen the restrictions on software.name?

### ISSUE THREAD

**Issue by edent** [jhass/nodeinfo#67]
In #15 software.name was changed from an enum to a free-text field.

However, the regex is `/^[a-z0-9-]+$/` - which only allows lower-case ASCII, digits, and a hyphen.

I'd like to be able to use a software name of "WordPress" with CamelCase - see https://github.com/Automattic/wordpress-activitypub/issues/436

Would it be possible to update the spec to allow `/^[A-Za-z0-9-]+$/`?

And, perhaps longer term, allow any UTF-8 string? That way, people could use non-Latin alphabets to identify their servers.

Thanks!

**Comment by jhass** [comment]
The field is intended as the canonical *technical* name of the software, thus the restriction. It is intended for example for aggregator sites to be able to group and filter instances based on the server software. Such implementations would likely need to implement certain normalization if we're too liberal here in the ecosystem. The value is not intended as a user presentable string, rather clients should provide a mapping to a user readable string if necessary and/or desired.

You can be more liberal in the description field as that has no direct technical usage beyond forwarding it to the user.
