### ISSUE TITLE
Split "services" into "inbound" and "outbound" values

### ISSUE THREAD

**Issue by annando** [jhass/nodeinfo#7]
As far as I understand, "services" is meant for third party networks that are connected via their API.
Since you cannot only post to these networks but can read posts from them as well, it would be great if "services" would be arranged like "protocols":

````
"services": {
        "inbound": [
            "appnet",
            "gnusocial",
            "pumpio",
            "twitter"
        ],
        "outbound": [
            "appnet",
            "blogger",
            "facebook",
            "gnusocial",
            "google",
            "libertree",
            "linkedin",
            "pumpio",
            "smtp",
            "tumblr",
            "twitter"
        ]
    }
````

**Comment by jhass** [comment]
Sounds sane. I hoped to have this kind of discussions months ago, but maybe we can still sneak it into 1.0 before the next diaspora or friendica release.

I know that Facebook has a policy against (seamlessly) pulling content via their API and mixing it with other similarly structured data. I could imagine Twitter has a similar policy, anybody knows more?

**Comment by annando** [comment]
Sorry, I'm mostly very late ... We are planning the next friendica release for the end of this month. It will be no problem to implement it there.

**Comment by jhass** [comment]
Since my question is unanswered I'd like to not include `twitter` in the list of valid values for `inbound`. If I receive no response till Sunday evening I'll implement the change.

**Comment by annando** [comment]
I don't have any information that Twitter is acting like Facebook. Additionally I think we shouldn't feel bound to some license stuff for the Nodeinfo - but only to what is implemented on the systems. And if some system is doing a Twitter import, I think the Nodeinfo should cover this.

**Comment by denschub** [comment]
Twitter does not allow any kind of "stream"-like embeds into other social networks (amongst others):

> Use Twitter Content or other data collected from users to create or maintain a separate status update or social network database or service.

([src](https://dev.twitter.com/overview/terms/policy#7.Update_Avoid_Replicating_the_Core_Twitter))

**Comment by jhass** [comment]
Given the above I've chosen to not include `twitter`, it's likely only a matter of time until Twitter enforces this like Facebook does. You can always communicate non-standard information via the metadata key.

**Comment by annando** [comment]
I adopted the changes: https://pirati.ca/nodeinfo/1.0 They will be part of the upcoming release 3.4.2

There are now two "services" sections: The one that is according to the specification and the one in the metadata that represents the real configuration.
