### ISSUE TITLE
add "nodeinfo_metadata_survey" and propose it as source of ideas for new nodeinfo changes

### ISSUE THREAD

**Issue by 6543** [jhass/nodeinfo#70]
Hi :wave: 

I did start an effort to collect all more widely used optional information fields:

https://codeberg.org/thefederationinfo/nodeinfo_metadata_survey

---
*(https://codeberg.org/thefederationinfo/nodeinfo_metadata_survey/issues/4)*

**Comment by 6543** [comment]
I would create a pull to link to this repo via the readme - if allowed.

Optional we could also mention in in the static spec website,
I just want to make sure that such effort will be accepted :)

**Comment by jhass** [comment]
Hey!

Great effort, this is certainly interesting information and I can see some utility in it!

Now the idea of the metadata field very much is for it to be actually not standardized, rather its intention is to be implementation specific and collect data that only really makes sense for one or a very small subset of the software out there. The usecases I'm imaging here are things like aggregators that are specific to one software or perhaps an area of the ecosystem, or one-off data analysis where somebody crawls the network (or obtains a dataset from an aggregator) and runs some analysis by hand on it. The point being that there would be no major benefit to ecosystem wide standardization.

So I do have to say I'm slightly hesitant to promote something like this in its current form. The entire existence of NodeInfo was sparked out of frustrations over competing standards or rather a lack of any formal standard at all. As it stands this would kind of introduce a new standard within the freedom the current one provides, thus actually restricting that original freedom in a way. I hope what I'm saying here makes somewhat sense.

I definitely can see how this project might seem a little stagnant and how evolving it through the means of a free form data structure within it makes sense from that perspective. However in reality please know I'm in no way opposed to pushing the main schema further and iterating on it. That is introducing new fields (optional and required alike) into the main schema that make sense and provide utility to the majority of the ecosystem and releasing a new schema version with those is not out of question at all for me at least, quite the opposite.

In that light I think what I'd love your project to become would be a kind of a survey, a database from which we can draw proposals for extending the standard. Like we see that the majority is having the ability of providing an instance name and exposing that in the metadata field, then let's consider introducing a place for that in the main schema. For an actual proposal also collecting some client usecases (what are people doing or expected to do with this new utility) would be quite important to me, but I think that shouldn't be hard for something that everybody is doing already, if they're doing it for a reason that's more than copying each other anyhow.

Anyhow, that's my first thoughts on this, please take it as my opinion and nothing as a final decision in case I haven't been clear enough on that :)

**Comment by 6543** [comment]
I agree that we dont need a new substandart in nodinfo standard.

I would like to see it more like a lookup table of ... this is commonly done by others ... so if the software interacts in a similar space (e.g. video streaming/sharing) ...

I start proposing [3 things](https://codeberg.org/thefederationinfo/nodeinfo_extension/issues?type=all&state=open&q=propose) out of my need to not relay on e.g. custom crawler for [mastodon](https://codeberg.org/thefederationinfo/nodeinfo-go/issues/5) for in the long run.

My main focus is on getting the [rewrite](https://codeberg.org/thefederationinfo/next) of https://the-federation.info ready.

It's nice to see that there is still great interest in maintaining this repo, and so I would really like to work with you to propose a new nodeinfo `v2.2`.

Using the `nodeinfo_extension` to collect **current state** of metadata usage and make it to one of the foundations to evolve the nodeinfo, is a great idea. In this regards I would still like to have it linked here then, but with a clear disclaimer that this is just a collection witch *can* be used for ideas in future iterations of this standard.

by the way there was also a intial effort to collect some needs at https://codeberg.org/thefederationinfo/the-federation.info/milestone/2005 , (the code of the legacy implementation of the statistics site).

From what I see, there are currently:
 - **node name**: not domain but the admin choosen utf8 encoded name
 - **node description**: a smal description e.g. focus of an instance
 - **admin conntact(s)**: how to get in contact to an node operator is important these days, and a formal way makes it way more easier

From my stats site provider perspective it also would be nice, to get tags/topics of an instance (if available) and a list to who is blocked or connected to who. This are more or less edgecases for the node operators so I dont focus on them right now.

If you (@jhass ) have time I would propose to just have a smal talk via [BBB](https://www.senfcall.de/) or jistsi, to get started.
just DM via [my matrix account](https://matrix.to/#/@marddl:obermui.de).

**Comment by jhass** [comment]
Sounds like we're aligned, great. I think if you would rebrand from "nodeinfo_extension" to something like "NodeInfo metadata survey" or similar that'd be self descriptive enough that we don't even need a disclaimer, and I'd be happy to add a link then :)

As for the actual iterations, I'd prefer an asynchronous working style to be honest so others can weight in and we have a record of what's discussed, hope you understand :) So I'd suggest just open dedicated issues for each change or even simply PRs if straight forward enough.
