### ISSUE TITLE
Include servername

### ISSUE THREAD

**Issue by annando** [jhass/nodeinfo#9]
By now only the name of the software is included. It should include all data from the former statistics.json - including the server name.

**Comment by jhass** [comment]
For diaspora I publish that in the free form metadata for now https://github.com/diaspora/diaspora/blob/develop/app/presenters/node_info_presenter.rb#L23

**Comment by jhass** [comment]
I'll close this issue due to lack of activity. Feel free to comment if you do want to further discuss this and then we can reopen.
