### ISSUE TITLE
Register in IANA

### ISSUE THREAD

**Issue by PichuChen** [jhass/nodeinfo#98]
Hello,

I saw you using `.well-known/nodeinfo` for this function. It's pretty cool.
But there are no register information on [IANA page](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml)

Would you register it?

**Comment by pfefferle** [comment]
Added a request: https://github.com/protocol-registries/well-known-uris/issues/50

**Comment by SuperTux88** [comment]
Thanks @pfefferle :heart:
