### ISSUE TITLE
Projects in README outdated? 

### ISSUE THREAD

**Issue by patrickReiis** [jhass/nodeinfo#99]
I'm new to this, so I could be understand it wrong.  

In the README.md section, it says that https://owncast.online/ and https://pleroma.social/ support it, but when accessing those websites with `.well-known/nodeinfo` it doesn't show up.

Example:  
https://owncast.online/.well-known/nodeinfo  
https://pleroma.social/.well-known/nodeinfo

**Comment by pfefferle** [comment]
These sites are the project site and they do not run the software. To test for NodeInfo support you have to check an owncast or pleroma instance.

**Comment by patrickReiis** [comment]
Ok, thanks. If you know any instance I can test and would like to send it here I'd appreciate.

Closing this issue.

**Comment by pfefferle** [comment]
In most of the project pages there is a section with example instances:

* https://pleroma.social/#featured-instances

Or yo can check fedidb:

* https://fedidb.org/software/owncast
* https://fedidb.org/software/pleroma
